defaults: &defaults
  adapter: postgresql
  host: localhost
  enconding: unicode
  template: template0

development:
  database: asset_pipeline_development
  username: postgres
  <<: *defaults

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgres
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...

test:
  database: asset_pipeline_test
  <<: *defaults
production:
  database: asset_pipeline
  username: postgres
  <<: *defaults
